# Generated by Django 2.2.6 on 2019-10-04 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publisher', models.CharField(default='', max_length=200)),
                ('publishedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('youtubeId', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
