# Generated by Django 2.2.6 on 2019-10-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='created_date',
            new_name='createdDate',
        ),
        migrations.AddField(
            model_name='video',
            name='commentCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='dislikeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='viewCount',
            field=models.BigIntegerField(default=0),
        ),
    ]
