# Generated by Django 2.2.6 on 2019-10-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_auto_20191004_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embedHtml',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.CharField(default='', max_length=500),
        ),
    ]
